# Math 124 - Programming for Mathematical Applications
UC Berkeley, Spring 2023

## Homework 3
Due Wednesday, February 8

### Problem 1

Define the matrix `A = [1:4  5:8  ones(Int64,4)]`.

Predict the result of performing the following operations in Julia (before checking your answers by running them). Note that the lines are meant to be run one-by-one in the same workspace, so when you e.g. change an array this will affect the subsequent statements.

a. `x = A[3,:]`


b. `B = A[2:2,1:3]`


c. `A[1,1] = 9 + A[2,3]`


d. `A[1:3,2:3] = [0 0; 0 0; 0 0]`


e. `A[1:2,2:3] = [1 3; 1 3]`


f. `y = A[1:4, 3]`


g. `A = [A [2 1 7; 7 4 5; ones(Int64,2,3)]]`


h. `C = A[[1,3],2]`


i. `D = A[[1,2,4],[1,3,4]]`

In [6]:
A = [1:4  5:8  ones(Int64,4)]

4×3 Matrix{Int64}:
 1  5  1
 2  6  1
 3  7  1
 4  8  1

In [4]:
# Prediction: Will print out all the elements on the third row
x = A[3,:]

3-element Vector{Int64}:
 3
 7
 1

In [5]:
# Prediction: Will print out elements 1-3 from row two
B = A[2:2,1:3]

1×3 Matrix{Int64}:
 2  6  1

In [7]:
# Prediction: Will change the value of element 1 in row 1 to 9 + the element 3 in row 2
A[1,1] = 9 + A[2,3]

10

In [8]:
# Prediction: Will change the matrix A to a matrix with two columns and three rows, with all the elements equal to 0
A[1:3,2:3] = [0 0; 0 0; 0 0]

3×2 Matrix{Int64}:
 0  0
 0  0
 0  0

In [9]:
# Prediction: Will change the matrix A to a matrix with two columns and two rows, with the first elements equal to 
# 1 and the second element equal to 2
A[1:2,2:3] = [1 3; 1 3]

2×2 Matrix{Int64}:
 1  3
 1  3

In [ ]:
y = A[1:4, 3]

In [ ]:
A = [A [2 1 7; 7 4 5; ones(Int64,2,3)]]

In [ ]:
C = A[[1,3],2]

In [ ]:
D = A[[1,2,4],[1,3,4]]

### Problem 2(a)

- Create a vector $x$ of the numbers $1, 0.99, 0.98, 0.97, . . . 0.01, 0$ in this order
- Using $x$, create a vector $y$ defined by the elementwise function $y_i = \sin 2\pi x_i$ for each element in $x$

### Problem 2(b)

Given the vector $y$, create:
  - A vector $v$ containing the first 25 elements of $y$
  - A vector $w$ containing elements of $y$ with indices from 50 to 75
  - A vector $z$ containing elements of $y$ with even indexes

### Problem 2(c)

Given the vector $y$, create:
  - A vector $v$ containing the same elements in the reverse order
  - A vector $w$ containing elements of $y$ which are smaller than -0.2
  - A vector $z$ of the *indices* in $y$ of elements greater than 0.5 (that is, the numbers $i$ for which $y_i>0.5$) 

### Problem 3

Given a matrix $A$, e.g. `A = [0 2 1; 3 1 0; 4 6 4; 2 0 2]`:

### Problem 3(a)
- Write code to create a matrix $B$ with 1’s at locations where $A$ has zeros and 0’s elsewhere

### Problem 3(b)


- Write code to create a matrix $C$ containing all 0’s except the maximum elements in each row of a (i.e. using the example matrix $A$, $C$ would be `[0 2 0; 3 0 0; 0 6 0; 2 0 2]`)

### Problem 4

Write a function `tridiag(a,b,c)` to create the following *tridiagonal* matrix:
$$
A = 
\begin{bmatrix}
   {b_1} & {c_1} & {   } & {   } & { 0 } \\
   {a_1} & {b_2} & {c_2} & {   } & {   } \\
   {   } & {a_2} & {b_3} & \ddots & {   } \\
   {   } & {   } & \ddots & \ddots & {c_{n-1}}\\
   { 0 } & {   } & {   } & {a_{n-1}} & {b_n}\\
\end{bmatrix}
$$
for vectors `a` and `c` of length $n-1$ and vector `b` of length $n$.

Test your function using e.g. `tridiag(1:4, 11:15, 21:24)`.

### Problem 5

Make a plot connecting the coordinates: $(1, 1)$, $(3, 1)$, $(2, 4)$, $(4, 2)$ and $(0,3)$ by a red line of linewidth 2. Use equal axis coordinates, and add grid lines.

### Problem 6

Plot the functions $f(x) = x$, $g(x) = 1/(1+x^3)$, $h(x) = e^{-x}$ and $z(x) = e^{-x^2}$ over the interval $x\in [0, 3]$. Describe your plots by using the functions `xlabel`, `ylabel`, `title` and `legend`.

### Problem 7

(Project Euler, Problem 25)

> The Fibonacci sequence is defined by the recurrence relation:
> 
> Fn = Fn−1 + Fn−2, where F1 = 1 and F2 = 1.
>
> Hence the first 12 terms will be:
> 
> F1 = 1
> F2 = 1
> F3 = 2
> F4 = 3
> F5 = 5
> F6 = 8
> F7 = 13
> F8 = 21
> F9 = 34
> F10 = 55
> F11 = 89
> F12 = 144
>
> The 12th term, F12, is the first term to contain three digits.
> 
> What is the index of the first term in the Fibonacci sequence to contain 1000 digits?

To solve this problem, we need to compute with integers much larger than the built-in type `Int128`. While Julia has support for larger integers, here you will write your own implementation to solve this problem using arrays and basic arithmetics.

We will represent the large integers by an array of length $n$ with integers between $0\ldots 9$. This is certainly not the most efficient way to solve this problem, but it works. More precisely, the value of a large integer represented by an array $X$ is
$$
\sum_{k=1}^n X[k] \cdot 10^{k-1}
$$
For example, with $n=5$ the array $X = [7,2,4,3,0]$ represents the integer $x=3427$.

We can define a helper function to print integers represented like this:

In [1]:
function print_bigint(X)
    for i = length(X):-1:1
        print(X[i])
    end
    println()
end

print_bigint (generic function with 1 method)

### Problem 7(a)

Write a function `int_to_bigint(x,n)` which converts a regular integer `x` (e.g. of type `Int64`) to an array of length `n` as described above. For example,
```julia
X = int_to_bigint(34278273,10);
println(X)
print_bigint(X)
```
should output
```
[3, 7, 2, 8, 7, 2, 4, 3, 0, 0]
0034278273
```

### Problem 7(b)

To solve the original problem, we also need a function to add two large integers represented by arrays. Implement a function `add_bigints(X,Y)` which computes the sum of the two numbers, and returns it in a new array. Use the standard addition with carry algorithm, and if there is a carry beyond the $n$th digit your code should run `error("Overflow")`.

For example, the code
```julia
x = 637465
y = 99827391
z = x + y
X = int_to_bigint(x,10)
Y = int_to_bigint(y,10)
Z = add_bigints(X,Y)
print_bigint(Z)
println(z)
```
should produce the output
```
0100464856
100464856
```
but if you change x to `9999999999` it should stop with an error.

### Problem 7(c)

Finally we can solve the original Fibonacci problem. Write a function `big_fibonacci(n)` which finds the first term in the sequence to contain `n` digits, prints that number (using `print_bigint`) and returns the index.

Try your function on the original problem, that is, run `big_fibonacci(1000)`.